import {
  MAX_REFERENCE_IMAGES_PER_ENQUIRY,
  REFERENCE_BUCKET,
  isAllowedMimeType,
  isWithinSizeLimit,
  type BucketId,
} from '@/lib/storage/buckets';
import { sanitiseText } from '@/lib/validation/enquiry';
import { probeImage, type ImageFormat } from './image-signature';
import {
  MAX_REFERENCE_IMAGE_EDGE,
  MAX_REFERENCE_IMAGE_MB,
  MAX_REFERENCE_IMAGE_PIXELS,
  MAX_REFERENCE_UPLOAD_BYTES,
  MIN_REFERENCE_IMAGE_EDGE,
} from './limits';

/**
 * Server-side validation of customer reference images.
 *
 * Requirements & SOW section 13: a customer may attach up to THREE inspiration
 * images, JPG/JPEG, PNG or WEBP, and those images are private. CLAUDE.md
 * repeats both the ceiling and the privacy rule.
 *
 * Everything here runs on the server and is the authority. The `accept` and
 * `multiple` attributes on the file input are a convenience for the customer;
 * they are trivially bypassed and are never trusted. Nothing reaches Supabase
 * Storage that has not passed every check below:
 *
 *   1. count       — never more than three, whatever was posted
 *   2. size        — 1 byte to 5 MB, matching the bucket's own limit
 *   3. declared    — the browser's Content-Type must be an accepted type
 *   4. content     — the BYTES must be that same type (magic-byte probe)
 *   5. dimensions  — inside sane bounds, so a decompression bomb is refused
 *   6. filename    — sanitised for display, never used to build a storage key
 *
 * Step 4 is the one that matters most: a `.jpg` that is really HTML, PHP, SVG
 * or a ZIP is rejected on its bytes, not on its label.
 */

/** A file that has passed every check and may be written to private storage. */
export type ValidatedReferenceImage = {
  /** The type proven by the file's own bytes, not the one the browser claimed. */
  mimeType: ImageFormat;
  bytes: Uint8Array;
  sizeBytes: number;
  width: number;
  height: number;
  /** Kept for display in the Admin Panel only. Never used to build a key. */
  originalFilename: string;
};

export type ReferenceImageValidation =
  | { success: true; images: ValidatedReferenceImage[] }
  | { success: false; message: string };

/** The same result shape, named for the admin path that also uses it. */
export type ImageUploadValidation = ReferenceImageValidation;

const TOO_MANY = `Please attach at most ${MAX_REFERENCE_IMAGES_PER_ENQUIRY} inspiration images. Choose your ${MAX_REFERENCE_IMAGES_PER_ENQUIRY} favourites and send them again.`;

const NOT_AN_IMAGE =
  'One of your files is not a JPG, PNG or WEBP image. Please choose your images again and resend the form.';

const TOO_LARGE = `Each inspiration image must be ${MAX_REFERENCE_IMAGE_MB} MB or smaller. Please choose your images again and resend the form.`;

const BAD_DIMENSIONS = `Each inspiration image must be at least ${MIN_REFERENCE_IMAGE_EDGE}x${MIN_REFERENCE_IMAGE_EDGE} pixels and no larger than ${MAX_REFERENCE_IMAGE_EDGE}x${MAX_REFERENCE_IMAGE_EDGE}. Please choose your images again and resend the form.`;

/**
 * Reduces a user-supplied filename to something safe to store and display.
 *
 * It is display metadata and nothing else — the storage key is generated by
 * `referenceObjectKey` and never contains any part of this value — but it is
 * still shown to an admin, so it must not carry a path, a control character or
 * a direction override that disguises what the file is.
 */
export function safeOriginalFilename(raw: string): string {
  const base = sanitiseText(raw).split(/[\\/]/).pop() ?? '';
  const cleaned = base.replace(/[^A-Za-z0-9 ._()-]/g, '').replace(/^\.+/, '');
  const trimmed = cleaned.slice(0, 120).trim();
  return trimmed.length > 0 ? trimmed : 'inspiration-image';
}

function isFileLike(value: unknown): value is File {
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof (value as File).arrayBuffer === 'function' &&
    typeof (value as File).size === 'number'
  );
}

/**
 * Decides whether a submitted part is an attachment at all.
 *
 * A file input the customer never touched is still submitted. Through a Server
 * Action it arrives as a zero-byte part with a placeholder name and a generic
 * `application/octet-stream` type; through a plain HTML POST it arrives as a
 * zero-byte part with an empty name. Neither is an attachment, and the field is
 * optional, so neither may produce an error.
 *
 * A file the customer really did choose that happens to be empty is a different
 * thing: the browser reports its real image type, so it is kept and then
 * refused by name further down, which is the honest answer.
 */
function isAttachment(file: File, bucket: BucketId): boolean {
  return file.size > 0 || isAllowedMimeType(bucket, file.type);
}

/**
 * The shared per-file gate.
 *
 * Every accepted upload in this application — a customer's private reference
 * image and an admin's portfolio photograph alike — goes through this function.
 * The two callers differ only in their bucket, their ceilings and the words
 * they use when something is wrong. The CHECKS are deliberately the same ones:
 * a portfolio upload arrives from an authenticated admin, but an authenticated
 * browser is still a browser, and a session does not make a payload safe.
 */
export type ImageValidationPolicy = {
  bucket: BucketId;
  maxFiles: number;
  maxTotalBytes: number;
  minEdge: number;
  maxEdge: number;
  maxPixels: number;
  messages: {
    tooMany: string;
    tooLarge: string;
    notAnImage: string;
    badDimensions: string;
  };
};

export async function validateImageUploads(
  formData: FormData,
  field: string,
  policy: ImageValidationPolicy,
): Promise<ReferenceImageValidation> {
  const candidates = formData
    .getAll(field)
    .filter(isFileLike)
    .filter((file) => isAttachment(file, policy.bucket));

  if (candidates.length === 0) return { success: true, images: [] };

  if (candidates.length > policy.maxFiles) {
    return { success: false, message: policy.messages.tooMany };
  }

  let total = 0;
  const images: ValidatedReferenceImage[] = [];

  for (const file of candidates) {
    if (!isWithinSizeLimit(policy.bucket, file.size)) {
      return { success: false, message: policy.messages.tooLarge };
    }

    total += file.size;
    if (total > policy.maxTotalBytes) {
      return { success: false, message: policy.messages.tooLarge };
    }

    // The browser's claim. It has to be plausible before the bytes are read,
    // so an obviously wrong request costs nothing.
    if (!isAllowedMimeType(policy.bucket, file.type)) {
      return { success: false, message: policy.messages.notAnImage };
    }

    const bytes = new Uint8Array(await file.arrayBuffer());

    // Guard against a Content-Length that disagreed with the body.
    if (!isWithinSizeLimit(policy.bucket, bytes.byteLength)) {
      return { success: false, message: policy.messages.tooLarge };
    }

    const probe = probeImage(bytes);

    // The bytes decide. A file whose content is not one of the accepted formats
    // is refused however it was labelled, and a file whose content disagrees
    // with its label is refused as well.
    if (!probe || probe.format !== file.type) {
      return { success: false, message: policy.messages.notAnImage };
    }

    if (
      probe.width < policy.minEdge ||
      probe.height < policy.minEdge ||
      probe.width > policy.maxEdge ||
      probe.height > policy.maxEdge ||
      probe.width * probe.height > policy.maxPixels
    ) {
      return { success: false, message: policy.messages.badDimensions };
    }

    images.push({
      mimeType: probe.format,
      bytes,
      sizeBytes: bytes.byteLength,
      width: probe.width,
      height: probe.height,
      originalFilename: safeOriginalFilename(file.name),
    });
  }

  return { success: true, images };
}

export const REFERENCE_IMAGE_POLICY: ImageValidationPolicy = {
  bucket: REFERENCE_BUCKET,
  maxFiles: MAX_REFERENCE_IMAGES_PER_ENQUIRY,
  maxTotalBytes: MAX_REFERENCE_UPLOAD_BYTES,
  minEdge: MIN_REFERENCE_IMAGE_EDGE,
  maxEdge: MAX_REFERENCE_IMAGE_EDGE,
  maxPixels: MAX_REFERENCE_IMAGE_PIXELS,
  messages: {
    tooMany: TOO_MANY,
    tooLarge: TOO_LARGE,
    notAnImage: NOT_AN_IMAGE,
    badDimensions: BAD_DIMENSIONS,
  },
};

/** Validates the files posted under `referenceImages`. */
export async function validateReferenceImageUploads(
  formData: FormData,
  field = 'referenceImages',
): Promise<ReferenceImageValidation> {
  return validateImageUploads(formData, field, REFERENCE_IMAGE_POLICY);
}
